# [1598번] 

In [41]:
# 2차원 배열에서 위치 차이를 구하는 프로그램입니다

In [36]:
import numpy as np
import math

grid = []
count = 1

for i in range(4):
    grid.append([0] * 10)
    
for i in range(10):
    for j in range(4):
        grid[j][i] = count
        count += 1

arr = np.array(grid)
print(arr)

start, stop = map(int, input().split())

start_row = (start-1) % 4          # 나머지가 몇번째 행에 있는지  
start_col = (start-1) // 4         # 몫이 몇번째 열에 있는지
stop_row = (stop-1) % 4
stop_col = (stop-1) // 4

#start_abs = abs(start_row) - abs(stop_row)  절대값 계산은 괄호 안에서 한번에 하는거임
#stop_abs = abs(start_col) - abs(stop_col)

start_abs = abs(start_row - stop_row)
stop_abs = abs(start_col - stop_col)

distance = start_abs + stop_abs
print(distance)

[[ 1  5  9 13 17 21 25 29 33 37]
 [ 2  6 10 14 18 22 26 30 34 38]
 [ 3  7 11 15 19 23 27 31 35 39]
 [ 4  8 12 16 20 24 28 32 36 40]]


 11 33


8


In [38]:
import math

# 사용자 입력
start, stop = map(int, input().split())

# 좌표 계산
start_row = (start - 1) // 4  # 몫이 행 번호
start_col = (start - 1) % 4  # 나머지가 열 번호
stop_row = (stop - 1) // 4
stop_col = (stop - 1) % 4

# 거리 계산
distance = abs(start_row - stop_row) + abs(start_col - stop_col)
print(distance)


 11 33


8


## 백준에 예시 이미지를 출력하지 않아도 됨 코드가 짧아짐